name: Cypress Tests (Ubuntu & Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Esegui il checkout del codice

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Configura la versione di Node.js

      - name: Run setup script
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            bash setup.sh  # Usa il setup.sh su Ubuntu
          else
            setup.bat  # Usa il setup.bat su Windows
        shell: bash  # Necessario per Ubuntu; Windows userà cmd automaticamente

      - name: Install Cypress binary
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            npx cypress install
          else
            npx cypress install
        shell: bash

      - name: Ensure Cypress executable permissions (Linux Only)
        if: matrix.os == 'ubuntu-latest'
        run: chmod +x ./node_modules/.bin/cypress

      - name: Run Cypress tests
        run: npx cypress run
