name: Cypress Setup Tests (Ubuntu & Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
  
      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/Cypress
            C:/Users/runneradmin/AppData/Local/Cypress/Cache
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Run setup script (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: bash setup.sh

      - name: Run setup script (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cmd /c setup.bat
        shell: cmd


      - name: Verify Cypress binary existence (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "Checking for Cypress binary in Ubuntu..."
          ls ~/.cache/Cypress || exit 1             

      - name: Verify Cypress binary existence (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          echo "Checking for Cypress binary in Windows..."
          powershell -Command "
            # Check if the folder exists
            if (Test-Path 'C:\Users\iacon\AppData\Local\Cypress\Cache') {
              Write-Output 'Cypress Cache folder found.'
              # List the contents of the directory for debugging
              Get-ChildItem 'C:\Users\iacon\AppData\Local\Cypress\Cache'
              # Check if Cypress binary exists in the folder
              if (Test-Path 'C:\Users\iacon\AppData\Local\Cypress\Cache\13.16.1\Cypress\Cypress.exe') {
                Write-Output 'Cypress binary found.'
              } else {
                Write-Error 'Cypress binary not found in cache! Exiting...'
                exit 1
              }
            } else {
              Write-Error 'Cypress Cache folder not found! Exiting...'
              exit 1
            }
          "
        shell: pwsh
        
            
      - name: Run Cypress tests
        run: npx cypress run
