name: Cypress Setup Tests (Ubuntu & Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
  
      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/Cypress
            C:/Users/iacon/AppData/Local/Cypress/Cache
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Run setup script (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: bash setup.sh

      - name: Run setup script (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cmd /c setup.bat
        shell: cmd


      - name: Verify Cypress binary existence (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "Checking for Cypress binary in Ubuntu..."
          ls ~/.cache/Cypress || exit 1             

            
      - name: Run Cypress tests
        run: npx cypress run
