
name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Clean and install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Ensure Cypress executable permissions
        run: chmod +x ./node_modules/.bin/cypress

      - name: Debug environment
        run: env

      - name: Run Cypress tests
        run: ./node_modules/.bin/cypress run
