name: Cypress Setup Tests (Ubuntu & Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/Cypress
            C:/Users/runneradmin/AppData/Local/Cypress/Cache
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Run setup script (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: bash setup.sh
            
      - name: Run setup script (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cmd /c setup.bat

      - name: Verify Cypress binary exists
        run: |
          if [[ ${{ matrix.os }} == 'windows-latest' ]]; then 
            if exist "C:\Users\runneradmin\AppData\Local\Cypress\Cache" (
              echo Cypress binary found.
            ) else (
              echo Cypress binary not found! Exiting...
              exit 1
            )
          else 
            ls ~/.cache/Cypress
          fi
        shell: cmd

      - name: Run Cypress tests
        run: npx cypress run
