name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Run setup script
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            setup.bat
          elif [ "${{ runner.os }}" == "Linux" ]; then
            bash setup.sh
          elif [ "${{ runner.os }}" == "macOS" ]; then
            bash setup.sh
          else
            echo "Unsupported OS: ${{ runner.os }}"
            exit 1

      - name: Ensure Cypress executable permissions
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: chmod +x ./node_modules/.bin/cypress

      - name: Run Cypress tests
        run: npx cypress run
