name: Cypress Tests (Ubuntu)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Esegui solo su Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Esegui il checkout del codice

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Configura la versione di Node.js

      - name: Run setup.sh script
        run: bash setup.sh  # Esegui il tuo script setup.sh

      - name: Ensure Cypress executable permissions
        run: chmod +x ./node_modules/.bin/cypress  # Assicura che Cypress abbia i permessi esecutivi

      - name: Run Cypress tests
        run: npx cypress run  # Esegui i test Cypress
